name: 🚀 Deploy Laravel Staging Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 31.97.225.238
          username: u925800196
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 65002
          script: |
            cd /home/u925800196/domains/medicsresearch.com/public_html/pmtoolstaging-api

            echo "Pull latest code"
            git pull origin staging

            echo "Install composer dependencies"
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

            echo "Clear Laravel cache"
            php artisan optimize:clear

            echo "Cache configs"
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

           

            echo "Deployment completed"
